#####Config File ########

# configuration
  clusters_geo_precision : 6
  default_store_radius_combination : 6-4

#Location of the area Settings
#we are using bangalore as of now
  ban_bbox_top_left :
    lat : 13.11091
    lon : 77.46253
  ban_bbox_bot_right :
    lat : 12.81581
    lon : 77.79075
  vpm_bbox_top_left :
    lat : 17.9598
    lon : 82.9289
  vpm_bbox_bot_right :
    lat : 17.4869
    lon : 83.6732
  ggn_bbox_top_left :
    lat : 28.52541
    lon : 76.96884
  ggn_bbox_bot_right :
    lat : 28.38898
    lon : 77.13294
  hyd_bbox_top_left :
    lat : 17.55631
    lon : 78.24462
  hyd_bbox_bot_right :
    lat : 17.26607
    lon : 78.62228
#path to files
  popular_products_file_path : data/popular_products.csv


