redis_host_dev: "localhost"
redis_port_dev: 6379

redis_host_stage: "localhost"
redis_port_stage: 6379

redis_host_qa: "localhost"
redis_port_qa: 6379

redis_host_perf: "redis.perf.olahack.in"
redis_port_perf: 6379

redis_host_prod: "redis-customer.internal.olastore.com"
redis_port_prod: 6379

redis_pool_maxActive: 5
redis_pool_maxIdle: 2
redis_pool_testOnBorrow: true
redis_pool_testOnReturn: true

