redis_host_dev: "localhost"
redis_port_dev: 6379
redis_passwd_dev: ""

redis_pool_maxActive: 5
redis_pool_maxIdle: 2
redis_pool_testOnBorrow: true
redis_pool_testOnReturn: true

geo_hash_city_key: "listing_cluster_city_"
geo_hash_key: "listing_cluster_geohash_"
