#####Config File ########


#Elastic Search configurations
ES:
  REST_API: http://localhost:9200
  GEO_HASH_INDEX: geo_hash_test
  GEO_HASH_INDEX_TYPE: hash_type
  CLUSTERS_INDEX: live_geo_clusters_test
  CLUSTERS_INDEX_TYPE: geo_cluster
  LISTING_INDEX: listing
  STORES_INDEX: stores
  STORES_INDEX_TYPE: store
  ES_SEARCH_END_POINT: _search
  ES_BULK_END_POINT: _bulk

#clusters configuration
Clusters:
  geo_precision : 7
  MAX_STORES: 4
  RADIUS: 6

#Location of the area Settings
#we are using bangalore as of now
Bbox:
  top_left :
    lat : 13.11091
    lon : 77.46253
  bot_right :
    lat : 12.81581
    long : 77.79075
Rank :
  product_factor : 0.35
  fnv_factor : 0.3
  nfnv_factor : 0.3



#path to files

Files :
  fnv_path : src/main/resources/fnv_pids.csv
  nfnv_path : src/main/resources/popular_nfnc.csv

