#####Config File ########


#Elastic Search configurations
  geo_hash_index_name: geo_hash
  geo_hash_index_type: hash_type
  clusters_index_name: live_geo_clusters
  clusters_index_type: geo_cluster
  listing_index_name: listing
  listing_index_type: list
  stores_index_name: stores_common
  stores_index_type: store

#API's
  es_search_api : http://localhost:9200/:index_name/:index_type/_search
  es_bulk_api : http://localhost:9200/:index_name/:index_type/_bulk
  es_index_api : http://localhost:9200/:index_name/:index_type
  es_delete_api : http://localhost:9200/:index_name/:index_type
  es_multi_delete_api : http://localhost:9200/:index_name1,:index_name2
  es_settings_api : http://localhost:9200/:index_name
  es_document_api : http://localhost:9200/:index_name/:index_type/:id
  es_bulk_api : http://localhost:9200/_bulk

#clusters configuration
  clusters_geo_precision : 7
  clusters_radius: 6

#Location of the area Settings
#we are using bangalore as of now
  bbox_top_left :
    lat : 13.11091
    lon : 77.46253
  bbox_bot_right :
    lat : 12.81581
    lon : 77.79075
#path to files
  popular_products_file_path : src/main/resources/popular_products.csv
